#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
title: Classic Films for Generation Z
# Short bio or description (displayed in the header)
description: A blog for the younger generation about classic films that shed light on topics that are not as frequently discussed.
theme: jekyll-theme-minimal
#
# !! DON'T EDIT BELOW THIS MESSAGE
#
# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
